### PR TITLE
Add unique field so that we can prevent double subscriptions

### PR DESCRIPTION
**Pull request by johnduffell**
This PR adds a new field to the states so that we can prevent duplicate subscriptions being added in zuora when someone only filled in the contribute form once.

This used to be done by identity id, but if the user is not logged in or is an unverified email address, we can't use any existing information associated with the identity account.

For (a lot) more details, see https://docs.google.com/document/d/14wYvCij4pYZ-0YIY46lO4DZhL4ZfHD2max6WAyLnkpQ/edit#

I have also bumped the scala version to the latest and removed the cross build.  It seems that all users of this library are on 2.12 anyway.

### CODE REVIEW

**Comment by johnduffell** [comment]
I thought about that, but that wouldn't prevent double submissions due to dodgy wifi etc and I wanted to make sure it was as watertight as possible.   I am not 100% sure what situations the existing deduplication was designed for though, whether it was just the step function repeating or whether it was also browser based shenanigans?

**Comment by johnduffell** [comment]
See what you mean.  There's a PR here https://github.com/guardian/support-frontend/pull/1039 to generate a token when the page with the form on it is loaded.  This means that once the user fills in the form, they can only ever add one recurring contribution from that page load.  This was just to cover the widest scope of duplicates possible while still avoiding crossing into existing data.  In fact I just realised this isn't quite as wide as it could be - it would actually be even better to set a cookie to avoid them going back around a second time.
I chatted with Jacob and it seems like we sometimes have bugs where we take multiple one off contributions, for example due to the button not being disabled properly or it seeming not to work.  So this would stop that issue.
Does that sound sensible, and if so do you think we should push the token in the other PR into a cookie instead of just per page?

**Comment by rupertbates** [comment]
> we sometimes have bugs where we take multiple one off contributions
These aren't handled by support-workers so wouldn't be affected by this change, unless you just mean that you're going to pass the token to the payment api as well?

> do you think we should push the token in the other PR into a cookie 
I would think that it's ok as is, if someone is trying something malicious, it will be straightforward for them to clear cookies anyway.

The only question I have is whether we need `requestId` and the access token or whether the token should now supersede `requestId`

**Comment by johnduffell** [comment]
good point, I will look into that.  Thanks for the pointer, that would certainly simplify things.

**Comment by johnduffell** [comment]
sorry didn't read your comment properly yesterday - re the multiple one off contributions I realised that's payment API, but my point was simply that it's easy to have browser issues that cause double submittions, hence my wanting to keep that being impossible for recurring.  However, it would be a nice improvement to follow your suggestion of passing the token to payment api too.

**Comment by rupertbates** [comment]
@jacobwinch any thoughts about replacing the requestId with the token which John is proposing? I don't think we need both but I'm not sure if you ever use it in debugging?

**Comment by johnduffell** [comment]
another point is I don't know all the things that call that endpoint.  Is it only the new and old contributions payment flows?  If so I could update them both to send a scope token.
Also there is a fundamental difference too, as there's not always a limited access scope. Although the client side will always send it through, the server side would also know if the person is logged in with a verified identity id.  In that case the scope is open to the whole identity id so it won't send it through to the step functions.
I feel like the request id is a separate question about do we even need it. and I'm starting to feel nervous about doing too much in this PR.
Does that make sense?

**Comment by johnduffell** [comment]
thanks! I'll push this out, then raise a support-frontend pr (which workes OK with the existing step functions, they seem to just discard the extra field) and finally I'll do the support workers part.

**Comment by johnduffell** [comment]
this is out as 0.33
https://oss.sonatype.org/content/repositories/releases/com/gu/support-models_2.12/0.33/

**Comment by johnduffell** [comment]
@rupertbates so it turns out that making a new session id is flawed and using request id as you suggestion is the only sensible solution.
This is because for every execution of the step functions, if the create zuora subscription step succeeds it will send an email and an event to analystics.  However, if a subscription is deduplicated relative to an existing one, the event and email will still be sent, even though the subscription was not created.
So actually we only want the create subscription stage to pass if there is a new subscription created as part of that step function execution.
This makes the step functions at least work sensibly in of themselves, and then the task of deduplicating would be for whatever calls the step functions.
If we really want the step functions to deduplicate, we could store both the session and request id in zuora, deduplicate on both, and only go to the analytics stage if it only deduplicated on request id but not on session id.  But we would still have to deal with the duplicates when someone wasn't logged in.

**Pull request merged**
